export  const projectlist = [
    {
        id: "1",
        name: "NayiNaurkri",
        description: "Online job Platform using Next JS that connect job seekers with employers.",
        detailedDescription:"NayiNaukri is an online platform that connect job seekers with employers. These websites provide a centralized location for job postings, allowing individuals to search and apply for jobs in various industries and locations. Job websites have become an essential tool in the job search process, providing convenient access to job opportunities and a means for employers to reach a wide pool of potential candidates.",
        image: "",
        languagesUsed: ["https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg",
    ],
        isFeatured: true,
        status: "Live",
        features: ["Job Post","Jon Search","Job Seeker Profile","Job Provider profile","Job Apply","Job Seeker Dashboard","Job Provider Dashboard","Job Seeker profile posting"],
        github: "https://github.com/AnkitRaj20/job-nextjs",
        url: "https://nayinaukri.netlify.app/",
        links: [],
        tag: "fullstack",
    },
    {
        id: "2",
        name: "RestoreMagic",
        description: "SaaS Platform for Image Manipulation using Next JS and Cloudinary API",
        detailedDescription:"Particularly adept with RestoreMagic, leveraging  Cloudinary API for innovative image manipulation features like Image Restore, Generative Fill, Object Remove, Object Recolor, and Background Remove. Proficient in integrating Stripe for seamless payment processing and Clerk for secure authentication.",
        image: "",
        languagesUsed: ["https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg",
    ],
        isFeatured: true,
        status: "Live",
        features: [" Image Restore", "Generative Fill","Object Remove", "Object Recolor","Background Remove","Clerk for secure authentication", "Stripe for accepting payment"],
        github: "https://github.com/AnkitRaj20/RestoreMagic",
        url: "https://restoremagic.vercel.app/",
        links: [],
        tag: "fullstack",
    },
    {
        id: "3",
        name: "JoyMaker",
        description: "Online Charity Application that helps you to donate money, food, clothes.",
        detailedDescription:"JoyMaker helps you to donate money, food, clothes etc. It is an ideal for people who want to help the poor people by donating or feeding them.The people can register and become volunteer and can provide any of these services.Working on the Covid- 19 response since the beginning of the crisis, JoyMaker is evolving its approach with changing needs on the ground.",
        image: "",
        languagesUsed: ["https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/php/php-original.svg","https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/css3/css3-original.svg","https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg","https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/mysql/mysql-original.svg"
    ],
        isFeatured: true,
        status: "Ready",
        features: ["Razorpay Payment Gateway Integration", "Donate Money","Donate Cooked or Raw Food", "Donate Clothes","Forgot Password"],
        github: "https://github.com/AnkitRaj20/joymaker/tree/main",
        url: null,
        links: [],
        tag: "fullstack",
    },
    {
        id: "4",
        name: "Personal Portfolio",
        description: "Sleek personal portfolio website made with NextJs,Tailwind CSS, ShadcnUI and Framer Motion.",
        detailedDescription:"This project is a personal portfolio website showcasing my skills and projects. It features a sleek and modern design implemented with Next.js,Tailwind CSS, ShadcnUI and Framer Motion.",
        image: "",
        languagesUsed: ["https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
    ],
        isFeatured: false,
        status: "Live",
        features: ["Sleek and modern design", "Built with Next.js","Animated transitions", "ShadcnUI"],
        github: "https://github.com/AnkitRaj20/portfolio-nextjs",
        url: "https://ankitcodes.vercel.app",
        links: [],
        tag: "frontend",
    },   
    {
        id: "5",
        name: "BrainCare",
        description: "Online Mental Health Website",
        detailedDescription:"An online mental health website where individuals  with shared experiences come together to foster mental well-being and motivation. Our platform provides a safe and supportive environment for open discussions, story sharing, and mutual encouragement.",
        image: "",
        languagesUsed: ["https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/php/php-original.svg","https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/css3/css3-original.svg","https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg","https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/mysql/mysql-original.svg"
    ],
        isFeatured: false,
        status: "Ready",
        features: [" Group Message for all people", "Separate groups for all genders, students","Zoom Api integration for meeting", "Post and View Story"],
        github: "https://github.com/AnkitRaj20/joymaker/tree/main",
        url: null,
        links: [],
        tag: "fullstack",
    },    
    {
        id: "6",
        name: "WeatherX",
        description: "Online Weather Website",
        detailedDescription:" Welcome to our weather website, where you can find all the latest and up-to-date weather information for your location and beyond. Our website provides accurate and reliable weather forecasts, current conditions, and real-time radar and satellite images to help you plan your day and stay prepared for any weather conditions",
        image: "",
        languagesUsed: ["https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/html5/html5-original.svg","https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/css3/css3-original.svg","https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg"
    ],
        isFeatured: false,
        status: "Live",
        features: ["Real time weather for all cities", "Searching","API integration"],
        github: "https://github.com/AnkitRaj20/WeatherX.github.io/tree/main",
        url: "https://weather-x-github-io.vercel.app",
        links: [],
        tag: "frontend",
    },
    {
        id: "7",
        name: "TextUtils",
        description: "Welcome to TextUtils - your go-to website for converting text to uppercase, lowercase, removing extra spaces and copying text with ease!",
        detailedDescription:"At TextUtils, we understand that working with text can be a time-consuming and tedious task. That's why we've created a platform that makes it easy for you to manipulate your text to suit your needs. With our simple yet powerful tools, you can quickly and easily transform your text to suit your requirements, whether you're a student, a writer, a marketer or a professional in any field.",
        image: "",
        languagesUsed: ["https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg","https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/css3/css3-original.svg"
    ],
        isFeatured: false,
        status: "Live",
        features: ["Text to Uppercase", "Text to Lowercase","Remove Extra Spaces","Copy Text"],
        github: "https://github.com/AnkitRaj20/react-TextUtils",
        url: "https://text-utils-iota.vercel.app/",
        links: [],
        tag: "frontend",
    },
   
];